
export const SAVE_IO_REF = "SAVE_IO_REF";
export const GET_TOTAL_USER = "GET_TOTAL_USER";
export const SAVE_TOTAL_USER = "GET_TOTAL_USER";
export const COMBINE_MESSAGE = "COMBINE_MESSAGE";
export const GET_USER_LIST_SUCESSFUL = "GET_USER_LIST_SUCESSFUL";
export const GET_ALL_CHAT= "GET_ALL_CHAT"
export const GET_ALL_CHAT_SUCESSFUL= "GET_ALL_CHAT_SUCESSFUL"
export const GET_PRIVATE_CHAT= "GET_PRIVATE_CHAT"
export const GET_PRIVATE_CHAT_SUCESSFUL= "GET_PRIVATE_CHAT_SUCESSFUL"